### ISSUE TITLE
貌似。。。依赖错误？

### ISSUE THREAD

**Issue by cxgreat2014** [phith0n/mooder#4]
hook@ubuntu:~/mooder$ python3 ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/hook/.local/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/hook/.local/lib/python3.5/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/home/hook/.local/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/hook/.local/lib/python3.5/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/hook/.local/lib/python3.5/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'registration'
hook@ubuntu:~/mooder$

**Comment by cxgreat2014** [comment]
hook@ubuntu:~/mooder$ sudo pip3 install registration
The directory '/home/hook/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/hook/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting registration
  Downloading registration-0.50.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-xxh_6c7f/registration/setup.py", line 3, in <module>
        from turbogears import finddata
    ImportError: No module named 'turbogears'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-xxh_6c7f/registration/
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
hook@ubuntu:~/mooder$ sudo pip3 install turbogears
The directory '/home/hook/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/hook/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting turbogears
  Downloading TurboGears-1.5.1.tar.gz (1.2MB)
    100% |████████████████████████████████| 1.2MB 1.1MB/s 
    Complete output from command python setup.py egg_info:
    TurboGears 1.5 requires a Python version between 2.4 and 2.7.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7idb43am/turbogears/
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
hook@ubuntu:~/mooder$

**Comment by cxgreat2014** [comment]
pip3 install -r requirements.txt
解决

**Comment by cxgreat2014** [comment]
建议把它写入文档，thanks

**Comment by phith0n** [comment]
忘记写了，感谢提醒！
